# Generated by Django 5.1.3 on 2024-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='criminalstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True)),
                ('category_of_crime', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_cases', models.CharField(blank=True, max_length=20, null=True)),
                ('login_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('date', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True)),
                ('login_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('house_name', models.CharField(blank=True, max_length=20, null=True)),
                ('place', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True)),
                ('post', models.CharField(blank=True, max_length=15, null=True)),
                ('login_id', models.BigIntegerField(blank=True, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
